server:
  port: 8848

spring:
  datasource:
    url: jdbc:h2:~/alarm-db
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      path: /h2-console
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-case: true

alarm:
  alarmThreshold: 3 #在 alarm-window-time时间内，发生3次进行告警
  alarmThresholdTime: 30  # 30分钟不能重复告警
  alarmWindowTime: 5 # 在 5分钟内，发生alarm-threshold次进行告警
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=dd3ca8bf-0761-4652-9b7a-0ecb08830fcf