server:
  port: 8848

spring:
  datasource:
    url: jdbc:h2:~/alarm-db
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      path: /h2-console  #h2嵌入式数据库控制台，可以通过浏览器访问
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-case: true
